Repository desihub/desitarget, pull requests merged in 2018-11, with the labels that each got.

#416 shuffle indices of mock targets in place
  .travis.yml
  py/desitarget/mock/build.py
Labels: bug, mocks

#421 fix install for cmx and sv1
  doc/changes.rst
  py/desitarget/sv1/__init__.py
  setup.py
Labels: bug

#424 update default mock catalogs; progress on Buzzard mocks and contaminants
  doc/changes.rst
  doc/mock_example/input.yaml
  py/desitarget/cuts.py
  py/desitarget/mock/build.py
  py/desitarget/mock/mockmaker.py
Labels: enhancement, mocks
